name: Auto-tag

on:
  push:
    branches:
      - master

jobs:
  auto-tag:
    runs-on: ubuntu-20.04
    steps:
      - uses: duderman/gh-gem-tag-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: v